trigger:
  branches:
    include:
    - '*'
    
pr:
- master

variables:
  - group: 'python-humio-build-release'
  - group: 'orch-key-vault-dev'
  - name: 'onPremLinuxAgent'
    value: 'DsbLinuxAgents'

stages:
- stage: Test
  displayName: Test python-humio
  jobs:
  - job: TestPythonHumio
    displayName: Run tests for PythonHumio
    pool:
      name: $(onPremLinuxAgent)
    steps:
    - bash: |
        pipenv install --dev
      displayName: Install pipenv dependencies
      workingDirectory:  $(System.DefaultWorkingDirectory)
    - bash: |
        pipenv run coverage run -m pytest
      displayName: Run pytest
      workingDirectory:  $(System.DefaultWorkingDirectory)
    - script: |
        bash <(curl -s https://codecov.io/bash)
      displayName: 'Upload to codecov.io'
      env:
        CODECOV_TOKEN: $(pyhumio-codecov-token )