trigger:
  branches:
    include:
    - 'release/'

jobs:
- job: PushToPip
  displayName: Authenticate and push to pip
  pool:
    name: $(onPremLinuxAgent)
  steps:
  - task: TwineAuthenticate@1
    displayName: 'Twine Authenticate Azure DevOps artifact'
    inputs:
      artifactFeed: $(artifact_feed_name)
  - bash: |
      pipenv install
    displayName: Install pipenv dependencies
  - bash: |
      pipenv install setuptools wheel
      pipenv python setup.py sdist bdist_wheel
      pipenv install twine
      pipenv twine upload -r automation-pip dist/*
      # repo url "https://dsbcp.pkgs.visualstudio.com/_packaging/automation-pip/pypi/upload"


