name: 'pyhumio release'

trigger:
  branches:
    include:
    - releases/*
    exclude:
    - '*'

variables:
  - group: 'python-humio-build-release'
  - name: 'onPremLinuxAgent'
    value: 'DsbLinuxAgents'

jobs:
- job: PushToPip
  displayName: Authenticate and push to pip
  pool:
    name: $(onPremLinuxAgent)
  steps:
  - task: TwineAuthenticate@1
    displayName: 'Twine Authenticate Azure DevOps artifact'
    inputs:
      artifactFeeds: $(artifact_feed_name)
  - bash: |
      pipenv install
      pipenv install setuptools wheel
      pipenv run python setup.py sdist bdist_wheel
      pipenv run install twine
      pipenv run twine upload -r $(artifact_feed_name) --config-file $(PYPIRC_PATH) dist/*
    displayName: Install pipenv dependencies and push package


